[features]
seeds = false
skip-lint = false

[programs.localnet]
tickettoken = "BnYanHjkV6bBDFYfC7F76TyYk6NA9p3wvcAfY1XZCXYS"

[programs.devnet]
tickettoken = "BnYanHjkV6bBDFYfC7F76TyYk6NA9p3wvcAfY1XZCXYS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kevin/Desktop/TicketToken-Platform/backend/services/minting-service/devnet-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
